# Basic setup
title:               "A Bread Baker’s Notebook"
description:         "A collection of work-in-progress sourdough bread experiments developed by Dana Johnson."
# url:                 http://127.0.0.1:4000
url:                 http://breadbakers-notebook.s3-website-us-west-2.amazonaws.com
repository:          https://github.com/dananjohnson/breadbakers-notebook
recipe-repository:   https://github.com/dananjohnson/bread-formulas
baseurl:             ""
typekit:             ily6mbo

# About/contact
author:
  name:              Dana Johnson
  email:             dana@sloopcreative.com

# Permalinks
permalink:           pretty

# Collections
collections:
  recipes:
    output:          true
    permalink:       /:path.html
    title:           "Bread Recipes"

# Front Matter Defaults
defaults:
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: default
  # Recipes
  - scope:
      path: _recipes
      type: recipes
    values:
      layout: recipe

# Custom vars
version:             0.0.1

# Jekyll configuration
markdown: kramdown
keep_files:
  - .git
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - bower.json
  - s3_website.yml
  - LICENSE.md
  - _recipes/LICENSE.md
  - _recipes/README.md
plugins:
  - jekyll-assets

# Plugin: Jekyll Assets
assets:
  prefix: "/assets"
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  assets:
    - "*.png"
    - "bundle.css"
